"""Read-only desktop delivery gate. Unit-test success is not live acceptance.

Browser evidence is a separate measured receipt, never generated by this check.
Requires viewport/zoom/scroll/refresh/focus/disconnect checks in BOTH renderers.
"""

import hashlib
import json
import os
import re
import subprocess
import sys
import time
from collections import Counter
from datetime import UTC, datetime
from html.parser import HTMLParser
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src/anthropic_throttle_proxy"
FILES = (
    "fleet_ui_config.py",
    "lanes.py",
    "ui/routes.py",
    "ui/presentation.py",
    "ui/templates/dashboard.html",
    "ui/templates/partials/stats.html",
    "ui/static/style.css",
)


def source_hash(base):
    digest = hashlib.sha256()
    for name in FILES:
        digest.update(name.encode())
        digest.update((base / name).read_bytes())
    return digest.hexdigest()


class Rows(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows, self.current, self.local = {}, None, None

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if attrs.get("id") == "stats-meta":
            self.local = attrs.get("data-local")
        if tag == "tr":
            self.current = attrs.get("data-subscription-id")
            if self.current:
                self.rows[self.current] = ""

    def handle_endtag(self, tag):
        if tag == "tr":
            self.current = None

    def handle_data(self, text):
        if self.current:
            self.rows[self.current] += text


def get(path):
    with urlopen(f"http://127.0.0.1:8765/{path}", timeout=8) as response:
        return response.read().decode()


def main():
    health = json.loads(get("__throttle/health"))
    build = Path(health["build"])
    assert str(build).startswith("/nix/store/"), "runtime is not a Nix package"
    unit = subprocess.check_output(
        [
            "/run/current-system/sw/bin/systemctl",
            "--user",
            "cat",
            "anthropic-throttle-proxy.service",
        ],
        text=True,
        timeout=8,
    )
    starts = "\n".join(line for line in unit.splitlines() if line.startswith("ExecStart="))
    packages = set(re.findall(r"/nix/store/[^/\s]+-anthropic-throttle-proxy-[0-9.]+", starts))
    package = str(Path(*build.parts[:4]))
    assert packages == {package}, "persistent start chain does not match running source"
    effective = subprocess.check_output(
        [
            "/run/current-system/sw/bin/systemctl",
            "--user",
            "show",
            "anthropic-throttle-proxy.service",
            "-p",
            "ExecStart",
        ],
        text=True,
        timeout=8,
    )
    assert package in effective, "effective start differs from the running package"
    expected = source_hash(SOURCE)
    assert source_hash(build) == expected, "running source does not match candidate"
    report_path = Path(
        os.environ.get("THROTTLE_LANES_FILE")
        or str(Path(os.environ.get("XDG_RUNTIME_DIR", "/run/user/1000")) / "throttle-lanes.json")
    )
    report = json.loads(report_path.read_text())
    stamp = datetime.strptime(report["generatedAt"], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)
    assert 0 <= time.time() - stamp.timestamp() <= 2 * report["intervalSeconds"]
    reported = {row["id"]: row for row in report["lanes"]}
    for path in ("ui", "ui/stats"):
        html = get(path)
        rows = Rows()
        rows.feed(html)
        assert rows.local == "false", "primary connection still displayed"
        assert "HEALTHY" not in html and "direct upstream" not in html
        assert "127.0.0.1:1" not in html and "Registered providers" in html
        for sid in ("codex:a", "codex:b", "codex:c", "zai:plan"):
            text = rows.rows[sid]
            icons = Counter({})
            for meter in reported[sid]["meters"]:
                assert str(meter["limitId"]) in text, f"raw scope missing from {sid}"
                duration = meter.get("windowMins")
                if duration in (300, 10080):
                    icons["⏱️" if duration == 300 else "📅"] += 1
            assert icons, f"no duration evidence for {sid}"
            assert all(text.count(icon) >= count for icon, count in icons.items()), sid
            assert not any(icon in text for icon in ("🅒", "🅰️", "🅱️"))
        assert not any("anthropic" in text.lower() for text in rows.rows.values())
        assert "observation time unknown" not in html and "report stale / untrusted" not in html
    receipt = Path(os.environ["DASHBOARD_BROWSER_RECEIPT"])
    browser = json.loads(receipt.read_text())
    assert browser["source_sha256"] == expected, "browser receipt belongs to another candidate"
    assert 0 <= time.time() - browser["observed_epoch"] < 900, "browser evidence is stale"
    cases = browser["cases"]
    for engine in ("firefox", "chromium"):
        for width in (390, 768, 1440, 2210):
            for zoom in (100, 200):
                matches = [
                    c
                    for c in cases
                    if (c["engine"], c["width"], c["zoom"]) == (engine, width, zoom)
                ]
                assert len(matches) == 1, "missing/duplicate browser case"
                case = matches[0]
                for check in (
                    "headings",
                    "scroll",
                    "refresh",
                    "focus",
                    "disconnect",
                    "no_page_overflow",
                ):
                    assert case[check] is True, (
                        f"rendered check failed: {engine}/{width}/{zoom}/{check}"
                    )
                shot = receipt.parent / case["screenshot"]
                assert hashlib.sha256(shot.read_bytes()).hexdigest() == case["screenshot_sha256"]
    print("PASS exact running source, row-scoped delivery and fresh two-renderer evidence")


if __name__ == "__main__":
    try:
        main()
    except (AssertionError, KeyError, ValueError, OSError) as error:
        print(f"NOT DELIVERED: {error}", file=sys.stderr)
        sys.exit(1)
